### ISSUE TITLE
years in header

### ISSUE THREAD

**Issue by PurpurTentakel97** [TechStreamConference/website-frontend#4]
add a drop down menu to be able to navigate to all years.

**Comment by mgerhold** [comment]
Maybe let's keep this for later? As long as we only have two years, a dropdown might look a bit "overkill".

**Comment by PurpurTentakel97** [comment]
The argument was, that visitors have to scroll all the way to the footer to see the old pages.
Maybe we should discuss if the even want to make the old pages that easy excisable or if it is good when you have to scroll.

When I put it into the header you can access it pretty fast. So so can see relatively easy what we did in the passed years. On the other hand you may not check that you actually seeing old content.

When I put it only in the footer the arguments are pretty much reversed.

**Comment by mgerhold** [comment]
For the 2025 event, I'd suggest putting a link to 2024 in the header. It's easy to access and shouldn't take up too much space. And when you're on the 2024 page, there should be a link to 2025. After 2025, we can think about how we want to solve that.

**Comment by PurpurTentakel97** [comment]
see #2 
This will always link to the current year.
because my understanding of clicking on a logo is to go to the main page. 
Do you mean that?
Or do I should add the 2025 year anyway than?

**Comment by PurpurTentakel97** [comment]
but yes.
it has the enhanced tag for a reason.

**Comment by mgerhold** [comment]
Let's maybe talk about this during a Discord call :)
